server:
  port: 9000

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      show-components: always
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true

spring:
  application:
    name: spring-cloud-gateway-secure-service

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: spring-cloud-gateway-secure-service
            client-secret: spring-cloud-gateway-secure-service-secret
            scope: openid
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_URL:http://localhost:8080}/auth/realms/PolarBookshop

  cloud:
    gateway:
      default-filters:
        - SaveSession
        - TokenRelay
      routes:
        - id: book-route
          uri: ${BOOK_SERVICE_URL:http://localhost:9001}
          predicates:
            - Path=/books/**
          filters:
            - name: Retry
              args:
                retries: 3
                method: GET
                backoff:
                  firstBackoff: 50ms
                  maxBackoff: 500ms
