server:
  port: 9000

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    root: INFO
    org.springframework.security: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      show-components: always
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true

spring:
  application:
    name: spring-cloud-gateway-secure-service

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: spring-cloud-gateway-secure-service
            client-secret: mCzlCPnSeX0PISC9dZLrMLpAuLB69b5X
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid
        provider:
          keycloak:
            authorization-uri: http://localhost:8080/realms/SpringBootKeycloak/protocol/openid-connect/auth
            token-uri: http://localhost:8080/realms/SpringBootKeycloak/protocol/openid-connect/token
            issuer-uri: http://localhost:8080/realms/SpringBootKeycloak
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: client-route
          uri: http://localhost:9001
          predicates:
            - Path=/**
